In [3]:
import pandas as pd
import numpy as np
import io
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [9]:
df = pd.read_csv("Real estate.csv")
df.shape
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

### 3. Step 3: Data Preprocessing

In [10]:
df_cleaned = df.drop(columns=['No'])


X = df_cleaned.drop(columns=['Y house price of unit area'])
y = df_cleaned['Y house price of unit area']

print("Features list:", list(X.columns))
print("Target:", y.name)

Features list: ['X1 transaction date', 'X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']
Target: Y house price of unit area

### 4. Step 4: Train-Test Split & Feature Scaling

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Train Size: {X_train.shape[0]}, Test Size: {X_test.shape[0]}")

Train Size: 331, Test Size: 83

### 5. Step 5: Models Training & Evaluation

In [13]:
# Models dictionary
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42)
}

In [16]:
# Evaluation loop
results = []
for name, model in models.items():
    # Model fit karna
    model.fit(X_train_scaled, y_train)
    # Predictions lena
    predictions = model.predict(X_test_scaled)

    # Metrics calculate karna
    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, predictions)

    results.append({
        "Model": name,
        "MAE": round(mae, 2),
        "RMSE": round(rmse, 2),
        "R2 Score (%)": round(r2 * 100, 2)
    })

# Results presentation
results_df = pd.DataFrame(results)
results_df

               Model   MAE  RMSE  R2 Score (%)
0  Linear Regression  5.31  7.31         68.11
1      Random Forest  3.96  5.71         80.59
2  Gradient Boosting  3.90  5.84         79.64